-- USERS
CREATE TABLE IF NOT EXISTS users(
    id SERIAL PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    email VARCHAR(100) NOT NULL UNIQUE,
    role VARCHAR(50) NOT NULL CHECK(role('client', 'freelancer', 'admin')), 
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
)



-- JOBS
-- PROPOSALS
-- MESSAGES